### ISSUE TITLE
Metadata (Platemap) Parsing Error

### ISSUE THREAD

**Issue by nbathreya** [czbiohub-sf/PhenoSight#22]
- The platemap format was hard-coded to handle 2 pre-defined formats that worked on datasets until TICM0036.
- Need to generalize the code to allow additional   ##configurations of platemap. This will work with TICM0044 and above datasets along with the previous ones.
- Need to add GUI for the user to select the conditions that would be compared.

**Comment by mattersoflight** [comment]
@nbathreya to clarify the data structure, we were discussing, we need two dictionaries 
* `well2condition` whose keys are `A1`, `A2`, `A3`, ... and values are the condition described in the platemap. This is easily parsed from the text. This should be a pandas data frame. 
* `condition2well` whose keys are unique condition identifiers (https://pandas.pydata.org/docs/reference/api/pandas.unique.html) and values are a list of well names, e.g., ['A1','A2','A3',..].

These two dictionaries should be updated by the callback that loads the platmap, and read by all the methods that parse the condition. 

The above data and code structure will enable generalization of PhenoSight to any platemap in our experients.

**Comment by mattersoflight** [comment]
@chad-liu-cz can you clarify if the `platemap-hpi.csv` report hours post-infection or seeding density? I recall from our last discussion that all imaging was done 48 hpi, moi-1. 

```
(base) [shalin.mehta@login-01 platemap]$ cat platemap-hpi.csv
,1,2,3,4,5,6,7,8,9,10,11,12
A,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
B,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
C,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
D,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
E,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
F,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
G,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
H,Uninfected,Uninfected,Uninfected,4,4,4,8,8,8,14,14,14
```

**Comment by chad-liu-cz** [comment]
Yes all imaging was done at 48 hpi and MOI 1. The `platemap-hpi.csv` was generated by @Soorya19Pradeep and she should be able to clarify more. From what I understand, the 4, 8 and 14 (technically 16) were cell density parameters, and she put that in place of the MOI to distinguish the conditions.

**Comment by Soorya19Pradeep** [comment]
@mattersoflight , what @chad-liu-cz says is correct. There is no other way to select the wells in plate based on the `platemap-hpi.csv`. It is hard-coded into PhenoSight to select the uninfected and highest MOI condition and doesn't presently let the user choose which conditions they want to compare. The user is able to choose the organelle marker based on the other platemap. 

This worked okay for TICM0044 as I wanted to compare the uninfected and highest seeding density conditions and I used seeding density instead of MOI. It was harder to analyze TICM0046 as I wanted to compare the uninfected and medium-density conditions and that required me to manipulate the plate map with wrong information.

Hence, I requested Nagendra for the feature so that the user can make the decision instead. It is also possible we will encounter other kinds of platemaps with other experiments. So hard-coding seemed a lot of work, adding different patterns of platemap with each analysis.
